version: '2'
services:

    db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: text_similarity
      
      networks:
        - main

    web:
      restart: always
      image: sanpreetai/text_similarity_mvc:mvc_commit
      command: python3 manage.py
      
      ports:
        - "2226:5000"

      links:
        - db
      depends_on:
        - db
      networks:
        - main

networks:
  main:
    driver: bridge

volumes:
  scan_file:
  
